### PR TITLE
 feat: support for aliases

### PR DESCRIPTION
**Pull request by aryehbeitz**
this is not ready. need to add support for second type of alias. pausing to work on integration and more tests on circular deps

### CODE REVIEW

**Comment by adrukh** [comment]
Change commit message to `test: aliases`? Or are you going to squash the actual `feat` changes into this one?

**Comment by aryehbeitz** [comment]
this is to be mainly a feature where we correctly support aliases, which includes tests
If no changes end up being needed, i'll squash and give it the `test:` prefix.

**Comment by aryehbeitz** [comment]
The idea here is as follows
Aliases can be used in the following ways:
1. inline alias version as version: we ask `composer` to use one version as another. e.g `1.7 as 1.6`
2. alias coming from an external repo; the alias is prefixed with `dev-`, as in `dev-my-bugfix as 1.7`. When we have this prefix. it means it's coming from an external repo, which we may have abilities to test in the future, but we want to display it as `my-bugfix` which is the branch in the external repo.

**Comment by aryehbeitz** [comment]
superseded by #10

**Pull request closed without merging**
